services:
  front:
    build:
      dockerfile: front.Dockerfile
    container_name: ${CONTAINER_NAME:-hanyang-front}
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - PORT=${PORT:-8000}
      - BACK_PORT=${BACK_PORT:-8001}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "${PORT:-8000}:${PORT:-8000}"

  back:
    build:
      dockerfile: back.Dockerfile
    container_name: ${BACK_CONTAINER_NAME:-hanyang-back}
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - PORT=${BACK_PORT:-8001}
      - DB_ENCRYPTION_KEY_B64=8SLlsBNPASoHEokCEb7eJUtqjpxXShhr
      - SESSION_SECRET_B64=${SESSION_SECRET_B64}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

    depends_on:
      - front

    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.${CONTAINER_NAME}-frontend.rule=Host(`${DOMAIN}`)"
    #   - "traefik.http.routers.${CONTAINER_NAME}-frontend.entrypoints=web,websecure"
    #   - "traefik.http.routers.${CONTAINER_NAME}-frontend.tls.certresolver=letsencrypt"
    #   - "traefik.http.routers.${CONTAINER_NAME}-frontend.service=${CONTAINER_NAME}-frontend"
    #   - "traefik.http.services.${CONTAINER_NAME}-frontend.loadbalancer.server.port=${PORT}"



networks:
  # traefik-net:
  #   external: true
  internal-net:
    internal: true