# .github/workflows/deploy-dev.yml
name: Build and Deploy to Development Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

      - name: Deploy to Development Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/kth88/services/product/
            gh repo clone kth88/HanyangAuto
            cd HanyangAuto
            docker-compose down --rmi all -v
            git fetch origin main
            git reset --hard origin/main
            git pull origin main

            export PROJECT_DIR=/home/kth88/services/product/HanyangAuto
            export DOCKER_IMAGE=kth88/hanyang-automation:latest
            export DOMAIN=hanyang.newme.dev

            chmod +x ./shFILES/start.sh
            ./shFILES/start.sh