# .github/workflows/deploy.yml

name: Build and Deploy to Personal Server

# main 브랜치에 push 이벤트가 발생했을 때 실행됩니다.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # 작업은 최신 Ubuntu 환경에서 실행됩니다.
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      # GitHub 저장소의 코드를 runner로 가져옵니다.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      # GitHub Secrets에 저장된 정보를 사용하여 Docker Hub에 로그인합니다.
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker 이미지 빌드 및 푸시
      # Dockerfile을 사용하여 이미지를 빌드하고, Docker Hub에 푸시합니다.
      # 이미지 태그는 'latest'로 지정됩니다.
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest # DOCKER_REPO 시크릿 사용

      # 4. 서버에 접속하여 배포 스크립트 실행
      # SSH를 통해 개인 서버에 접속하고, shFILES/start.sh 스크립트를 실행합니다.
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            chmod +x ./shFILES/start.sh
            ./shFILES/start.sh
